export function formatHelp(): string {
  return [
    'osm2arango',
    '',
    'Usage:',
    '  osm2arango <command> [args] [--flags]',
    '',
    'Commands:',
    '  bootstrap                 Create DB, collection, and indexes',
    '  download <region|url>     Download Geofabrik extract (.osm.pbf)',
    '  import <file>             Import a .osm.pbf (via osmium) or .ndjson',
    '',
    'Global connection flags (override env):',
    '  --arango-url <url>        ARANGO_URL (default: http://127.0.0.1:8529)',
    '  --arango-db <name>        ARANGO_DB (required for bootstrap/import)',
    '  --arango-user <user>      ARANGO_USER (default: root)',
    '  --arango-pass <pass>      ARANGO_PASS (required)',
    '',
    'bootstrap flags:',
    '  --collection <name>       default: osm_features',
    '',
    'download flags:',
    '  --out-dir <dir>           default: data',
    '  --base-url <url>          default: https://download.geofabrik.de',
    '',
    'import flags:',
    '  --collection <name>       default: osm_features',
    '  --adapter <name>          osmium-geojsonseq | ndjson (auto; .ndjson => ndjson)',
    '  --chunk-mb <n>            default: 8',
    '  --concurrency <n>         default: 2',
    '  --on-duplicate <mode>     error | update | replace | ignore (default: update)',
    '  --unsupported-geometry <mode> skip | keep | error (default: skip)',
    '',
    'Examples:',
    '  osm2arango bootstrap',
    '  osm2arango download europe/germany/berlin',
    '  osm2arango import data/berlin-latest.osm.pbf',
    '',
  ].join('\n')
}
