export function formatHelp(): string {
  return [
    'osm2arango',
    '',
    'Usage:',
    '  osm2arango <command> [args] [--flags]',
    '',
    'Commands:',
    '  bootstrap                 Create DB, collection, and indexes',
    '  download <region|url>     Download Geofabrik extract (.osm.pbf)',
    '  import <file>             Import a .osm.pbf (via osmium) or .ndjson',
    '  wizard                    Interactive import wizard (Geofabrik tree + guided settings)',
    '',
    'Global connection flags (override env):',
    '  --arango-url <url>        ARANGO_URL (default: http://127.0.0.1:8529)',
    '  --arango-db <name>        ARANGO_DB (required for bootstrap/import)',
    '  --arango-user <user>      ARANGO_USER (default: root)',
    '  --arango-pass <pass>      ARANGO_PASS (required)',
    '',
    'bootstrap flags:',
    '  --collection <name>       default: osm_features',
    '  --indexes <profile>       all | none | geo | tags (default: all)',
    '',
    'download flags:',
    '  --out-dir <dir>           default: data',
    '  --base-url <url>          default: https://download.geofabrik.de',
    '',
    'import flags:',
    '  --collection <name>       default: osm_features',
    '  --adapter <name>          osmium-geojsonseq | ndjson (auto; .ndjson => ndjson)',
    '  --profile <name>          places | amenities | recreation | all (default: places)',
    '  --chunk-mb <n>            default: 8',
    '  --max-line-mb <n>         default: 8 (skip extremely large lines to keep import stable)',
    '  --concurrency <n>         default: 2',
    '  --on-duplicate <mode>     error | update | replace | ignore (default: update)',
    '  --unsupported-geometry <mode> skip | keep | error (default: skip)',
    '  --import-transport <name> arangojs | node-http | curl (default: curl if available, else arangojs)',
    '  --invalid-json <mode>     error | skip (default: error)',
    '  --osmium-index-type <t>   Pass through to `osmium export --index-type` (advanced)',
    '  --osmium-geometry-types <t> Pass through to `osmium export --geometry-types`',
    '  --dry-run                 Parse and count, but do not write to ArangoDB',
    '  --no-progress             Disable progress output',
    '',
    'wizard flags:',
    '  --region <id|path|url>    Preselect Geofabrik region (advanced)',
    '  --scope <s>               region | children | leaves',
    '  --plan                    Print plan only (no download/import/write)',
    '  --yes                     Accept recommended defaults where possible',
    '',
    'Examples:',
    '  osm2arango bootstrap',
    '  osm2arango download europe/germany/berlin',
    '  osm2arango import data/berlin-latest.osm.pbf',
    '  osm2arango wizard',
    '',
  ].join('\n')
}
